title: RPG Mechanics Analysis
description: Data analysis of RPG mechanics and their impact on sales
baseurl: "/rpg-mechanics-analysis"   # repo name
url: "https://meloukiali96.github.io"
theme: minima
